theme: jekyll-theme-cayman
title: My Blog
description: Welcome to my personal blog.

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

